#ifndef RW_ENGINE_RENDERER_GLOBAL_ILLUMINATION_METAL_COMPAT_HPP
#define RW_ENGINE_RENDERER_GLOBAL_ILLUMINATION_METAL_COMPAT_HPP
#include "Renderer/GlobalIllumination/Metal/GlobalIlluminationMetal.hpp"
#endif
