bool decodeTopology(std::uint32_t symbols,std::uint32_t faces,std::uint32_t encoded_vertices,std::uint32_t split_count,const std::vector<SplitEvent>& splits,ValenceTraversal& traversal,CornerTable* t,std::string* error){
    if(!t||encoded_vertices>UINT32_MAX-split_count||!t->reset(faces,encoded_vertices+split_count))return fail(error,"invalid Draco EdgeBreaker table size");
    traversal.valence.assign(static_cast<std::size_t>(encoded_vertices+split_count),0);
    std::vector<int> active,isolated;std::unordered_map<int,int> split_active;std::size_t split_cursor=0;int decoded_faces=0;
    for(std::uint32_t sid=0;sid<symbols;++sid){std::uint32_t symbol=0;if(!traversal.next(&symbol))return fail(error,"invalid Draco valence symbol stream");const int corner=decoded_faces++*3;bool check_split=false;int merge_dest=-1,merge_source=-1;
        if(symbol==0u){if(active.empty())return fail(error,"Draco C symbol has no active edge");const int a=active.back(),vx=t->vertex(t->next(a)),b=t->next(t->leftMost(vx));if(a==b||a<0||b<0||t->oppositeCorner(a)>=0||t->oppositeCorner(b)>=0)return fail(error,"invalid Draco C topology");const int va=t->vertex(t->previous(a)),vb=t->vertex(t->next(b));if(vx==va||vx==vb||!t->setOpposite(a,corner+1)||!t->setOpposite(b,corner+2)||!t->map(corner,vx)||!t->map(corner+1,vb)||!t->map(corner+2,va))return fail(error,"invalid Draco C mapping");t->setLeftmost(va,corner+2);active.back()=corner;}
        else if(symbol==3u||symbol==5u){if(active.empty())return fail(error,"Draco L/R symbol has no active edge");const int a=active.back();if(t->oppositeCorner(a)>=0)return fail(error,"occupied Draco active edge");int o=0,l=0,r=0;if(symbol==5u){o=corner+2;l=corner+1;r=corner;}else{o=corner+1;l=corner;r=corner+2;}if(!t->setOpposite(o,a))return fail(error,"invalid Draco L/R edge");const int nv=t->addVertex();if(nv<0||!t->map(o,nv))return fail(error,"too many Draco vertices");t->setLeftmost(nv,o);const int rv=t->vertex(t->previous(a)),lv=t->vertex(t->next(a));if(!t->map(r,rv)||!t->map(l,lv))return fail(error,"invalid Draco L/R mapping");t->setLeftmost(rv,r);active.back()=corner;check_split=true;}
        else if(symbol==1u){if(active.empty())return fail(error,"Draco S symbol has no active edge");const int b=active.back();active.pop_back();const auto si=split_active.find(static_cast<int>(sid));if(si!=split_active.end())active.push_back(si->second);if(active.empty())return fail(error,"Draco S symbol missing second edge");const int a=active.back();if(a==b||t->oppositeCorner(a)>=0||t->oppositeCorner(b)>=0||!t->setOpposite(a,corner+2)||!t->setOpposite(b,corner+1))return fail(error,"invalid Draco S topology");const int vp=t->vertex(t->previous(a)),van=t->vertex(t->next(a)),vbp=t->vertex(t->previous(b));if(!t->map(corner,vp)||!t->map(corner+1,van)||!t->map(corner+2,vbp))return fail(error,"invalid Draco S mapping");t->setLeftmost(vbp,corner+2);int merge=t->next(b);const int merged=t->vertex(merge);if(vp<0||merged<0)return fail(error,"invalid Draco S merge");merge_dest=vp;merge_source=merged;t->setLeftmost(vp,t->leftMost(merged));const int first=merge;while(merge>=0){if(!t->map(merge,vp))return fail(error,"invalid Draco S merge mapping");merge=t->swingLeft(merge);if(merge==first)return fail(error,"closed Draco S merge ring");}t->isolate(merged);isolated.push_back(merged);active.back()=corner;}
        else if(symbol==7u){const int a=t->addVertex(),b=t->addVertex(),c=t->addVertex();if(a<0||b<0||c<0||!t->map(corner,a)||!t->map(corner+1,b)||!t->map(corner+2,c))return fail(error,"too many Draco E vertices");t->setLeftmost(a,corner);t->setLeftmost(b,corner+1);t->setLeftmost(c,corner+2);active.push_back(corner);check_split=true;}
        else return fail(error,"invalid Draco valence topology symbol");
        if(merge_dest>=0&&!traversal.merge(merge_dest,merge_source))return fail(error,"invalid Draco valence merge");
        if(!traversal.reached(*t,corner))return fail(error,"invalid Draco valence state");
        if(check_split){const int enc=static_cast<int>(symbols)-static_cast<int>(sid)-1;SplitEvent sp;while(findSplit(splits,enc,&split_cursor,&sp)){if(sp.split<0||active.empty())return fail(error,"invalid Draco topology split");const int top=active.back(),new_active=sp.right?t->next(top):t->previous(top),decoder_split=static_cast<int>(symbols)-sp.split-1;split_active[decoder_split]=new_active;}}
    }
    while(!active.empty()){const int a=active.back();active.pop_back();bool interior=false;if(!traversal.start_faces.bit(&interior))return fail(error,"truncated Draco start-face stream");if(!interior)continue;if(decoded_faces>=static_cast<int>(faces))return fail(error,"too many Draco start faces");const int vn=t->vertex(t->next(a)),b=t->next(t->leftMost(vn)),vx=t->vertex(t->next(b)),c=t->next(t->leftMost(vx));if(a==b||a==c||b==c||a<0||b<0||c<0||t->oppositeCorner(a)>=0||t->oppositeCorner(b)>=0||t->oppositeCorner(c)>=0)return fail(error,"invalid Draco interior start face");const int vp=t->vertex(t->next(c)),nc=decoded_faces++*3;if(!t->setOpposite(nc,a)||!t->setOpposite(nc+1,b)||!t->setOpposite(nc+2,c)||!t->map(nc,vx)||!t->map(nc+1,vp)||!t->map(nc+2,vn))return fail(error,"invalid Draco start face");}
    if(decoded_faces!=static_cast<int>(faces)) return fail(error,"Draco EdgeBreaker face count mismatch");
    const int vc=compact(*t,isolated);
    if(vc<0||static_cast<std::uint32_t>(vc)>encoded_vertices) return fail(error,"Draco EdgeBreaker vertex count mismatch");
    return true;
}

bool decodeSeams(const CornerTable& t,ValenceTraversal& tr,DracoEdgeBreakerTopology* out,std::string* error){out->seams.assign(tr.seams.size(),std::vector<std::uint8_t>(t.corner_vertex.size(),0));for(std::size_t c=0;c<t.corner_vertex.size();++c){const int o=t.oppositeCorner(static_cast<int>(c));if(o<0){for(auto& s:out->seams)s[c]=1;continue;}if(static_cast<std::size_t>(o)<c)continue;for(std::size_t i=0;i<tr.seams.size();++i){bool v=false;if(!tr.seams[i].bit(&v))return fail(error,"truncated Draco seam stream");if(v){out->seams[i][c]=1;out->seams[i][static_cast<std::size_t>(o)]=1;}}}return true;}

} // namespace
