bool decodeIntegerPortable(Reader& r,const Topology& topology,const std::vector<Record>& decoded,Record *record,std::string *error) {
    if (!record) return false;
    const unsigned comps = record->decoder_type == 3u ? 2u : record->output.components;
    const std::size_t entries = topology.point_corner.size();
    if (comps == 0u || entries > std::numeric_limits<std::size_t>::max() / comps) return fail(error, "Draco attribute value count overflows");
    const std::size_t count = entries * comps;
    std::int8_t prediction=-2,transform=0;if(!r.i8(&prediction))return fail(error,"truncated Draco prediction scheme");if(prediction!=-2&&!r.i8(&transform))return fail(error,"truncated Draco prediction transform");if(prediction!=-2&&transform!=1&&transform!=3)return fail(error,"unsupported Draco prediction transform");record->prediction=prediction;
    std::uint8_t compressed=0;if(!r.u8(&compressed))return fail(error,"truncated Draco integer compression flag");std::vector<std::uint32_t> symbols(count,0u);if(compressed){if(!decodeSymbols(r,count,comps,&symbols))return fail(error,"invalid Draco integer symbol stream");}else{std::uint8_t bytes=0;if(!r.u8(&bytes)||bytes==0||bytes>4)return fail(error,"invalid Draco integer byte width");for(auto& v:symbols)if(!littleUnsigned(r,bytes,&v))return fail(error,"truncated Draco integer data");}
    std::vector<std::int32_t> corrections(count,0);const bool positive=prediction!=-2&&transform==3;for(std::size_t i=0;i<count;++i)corrections[i]=positive?static_cast<std::int32_t>(symbols[i]):zigzag(symbols[i]);
    std::array<std::vector<std::uint8_t>,4> crease_bits;std::vector<std::uint8_t> orientations,flip_bits;std::int32_t wrap_min=0,wrap_max=0,normal_max=0;
    if(prediction==4){for(auto& bits:crease_bits){std::uint32_t n=0;if(!r.var32(&n))return fail(error,"truncated Draco constrained flags");if(n&&!readPredictionBits(r,n,&bits))return fail(error,"invalid Draco constrained flags");}}
    else if(prediction==5){std::uint32_t n=0;if(!r.u32(&n))return fail(error,"truncated Draco texcoord orientation count");std::vector<std::uint8_t> raw;if(n&&!readPredictionBits(r,n,&raw))return fail(error,"invalid Draco texcoord orientation stream");bool last=true;for(auto bit:raw){if(bit==0)last=!last;orientations.push_back(last?1u:0u);}}
    else if(prediction==6){std::int32_t center=0;if(transform!=3||!r.i32(&normal_max)||!r.i32(&center))return fail(error,"invalid Draco geometric normal transform");if(!readPredictionBits(r,entries,&flip_bits))return fail(error,"invalid Draco normal flip stream");}
    if(prediction!=-2&&prediction!=6){if(transform==1){if(!r.i32(&wrap_min)||!r.i32(&wrap_max)||wrap_min>wrap_max)return fail(error,"invalid Draco wrap transform");}else{std::int32_t center=0;if(!r.i32(&normal_max)||!r.i32(&center))return fail(error,"invalid Draco normal transform");}}
    std::vector<std::int32_t> original(count,0);auto corr=[&](std::size_t e){std::vector<std::int32_t> v(comps);for(unsigned c=0;c<comps;++c)v[c]=corrections[e*comps+c];return v;};auto prev=[&](std::size_t e){std::vector<std::int32_t> v(comps,0);if(e)for(unsigned c=0;c<comps;++c)v[c]=original[(e-1)*comps+c];return v;};auto write=[&](std::size_t e,const std::vector<std::int32_t>& v){for(unsigned c=0;c<comps;++c)original[e*comps+c]=v[c];};auto apply=[&](const std::vector<std::int32_t>& p,const std::vector<std::int32_t>& c){std::vector<std::int32_t> o;wrapValue(p,c,wrap_min,wrap_max,&o);return o;};
    if(prediction==-2){original=corrections;}
    else if(prediction==0){for(std::size_t e=0;e<entries;++e)write(e,apply(prev(e),corr(e)));}
    else if(prediction==1){for(std::size_t e=0;e<entries;++e){std::vector<std::int32_t> p;if(e==0||!parallelogram(topology,e,original,comps,&p))p=prev(e);write(e,apply(p,corr(e)));}}
    else if(prediction==4){std::array<std::size_t,4> pos{};for(std::size_t e=0;e<entries;++e){std::vector<std::vector<std::int32_t>> preds;for(int corner:incidentCorners(topology,static_cast<std::uint32_t>(e))){const int o=topology.opposite[static_cast<std::size_t>(corner)];if(o<0)continue;const auto a=topology.corner_point[static_cast<std::size_t>(o)],b=topology.corner_point[static_cast<std::size_t>(Topology::next(o))],cpoint=topology.corner_point[static_cast<std::size_t>(Topology::prev(o))];if(a>=e||b>=e||cpoint>=e)continue;std::vector<std::int32_t> p(comps);for(unsigned c=0;c<comps;++c)p[c]=original[static_cast<std::size_t>(b)*comps+c]+original[static_cast<std::size_t>(cpoint)*comps+c]-original[static_cast<std::size_t>(a)*comps+c];preds.push_back(std::move(p));if(preds.size()==4u)break;}std::vector<std::int32_t> p(comps,0);std::size_t used=0;const std::size_t ctx=preds.empty()?0u:preds.size()-1u;for(const auto& candidate:preds){if(pos[ctx]>=crease_bits[ctx].size())return fail(error,"Draco constrained flag underflow");const bool crease=crease_bits[ctx][pos[ctx]++]!=0;if(crease)continue;++used;for(unsigned c=0;c<comps;++c)p[c]+=candidate[c];}if(!used)p=prev(e);else for(auto& v:p)v/=static_cast<std::int32_t>(used);write(e,apply(p,corr(e)));}}
    else if(prediction==5){if(comps!=2u)return fail(error,"Draco texcoord prediction requires two components");std::size_t op=orientations.size();for(std::size_t e=0;e<entries;++e){std::vector<std::int32_t> p=prev(e);const int corner=topology.point_corner[e];if(corner>=0){const auto n=topology.corner_point[static_cast<std::size_t>(Topology::next(corner))],pr=topology.corner_point[static_cast<std::size_t>(Topology::prev(corner))];if(n<e&&pr<e){const std::array<std::int32_t,2> nu={original[static_cast<std::size_t>(n)*2u],original[static_cast<std::size_t>(n)*2u+1u]},pu={original[static_cast<std::size_t>(pr)*2u],original[static_cast<std::size_t>(pr)*2u+1u]};if(nu==pu)p={pu[0],pu[1]};else{const auto tip=portablePosition(decoded,static_cast<std::uint32_t>(e)),np=portablePosition(decoded,n),pp=portablePosition(decoded,pr);const std::int64_t pnx=static_cast<std::int64_t>(pp[0])-np[0],pny=static_cast<std::int64_t>(pp[1])-np[1],pnz=static_cast<std::int64_t>(pp[2])-np[2];const std::uint64_t pn2=static_cast<std::uint64_t>(pnx*pnx+pny*pny+pnz*pnz);if(pn2){const std::int64_t cnx=static_cast<std::int64_t>(tip[0])-np[0],cny=static_cast<std::int64_t>(tip[1])-np[1],cnz=static_cast<std::int64_t>(tip[2])-np[2],dot=cnx*pnx+cny*pny+cnz*pnz,du=static_cast<std::int64_t>(pu[0])-nu[0],dv=static_cast<std::int64_t>(pu[1])-nu[1],xu=du*dot+static_cast<std::int64_t>(nu[0])*static_cast<std::int64_t>(pn2),xv=dv*dot+static_cast<std::int64_t>(nu[1])*static_cast<std::int64_t>(pn2),dx=cnx*static_cast<std::int64_t>(pn2)-pnx*dot,dy=cny*static_cast<std::int64_t>(pn2)-pny*dot,dz=cnz*static_cast<std::int64_t>(pn2)-pnz*dot;const long double dist=static_cast<long double>(dx)*dx+static_cast<long double>(dy)*dy+static_cast<long double>(dz)*dz;const std::uint64_t cxpn=dist>0?static_cast<std::uint64_t>(std::sqrt(dist/static_cast<long double>(pn2))):0u;const std::int64_t cxu=dv*static_cast<std::int64_t>(cxpn),cxv=-du*static_cast<std::int64_t>(cxpn);if(op==0u)return fail(error,"Draco texcoord orientation underflow");const bool orientation=orientations[--op]!=0;const std::int64_t unum=orientation?xu+cxu:xu-cxu,vnum=orientation?xv+cxv:xv-cxv;p[0]=static_cast<std::int32_t>(unum/static_cast<std::int64_t>(pn2));p[1]=static_cast<std::int32_t>(vnum/static_cast<std::int64_t>(pn2));}}}else if(pr<e){p={original[static_cast<std::size_t>(pr)*2u],original[static_cast<std::size_t>(pr)*2u+1u]};}else if(n<e){p={original[static_cast<std::size_t>(n)*2u],original[static_cast<std::size_t>(n)*2u+1u]};}}write(e,apply(p,corr(e)));}}
    else if(prediction==6){if(comps!=2u||flip_bits.size()!=entries)return fail(error,"invalid Draco normal prediction");unsigned bits=0;for(std::uint32_t v=normal_max>0?static_cast<std::uint32_t>(normal_max):0u;v;v>>=1u)++bits;if(bits==0)return fail(error,"invalid Draco normal max");const std::int64_t maxq=(std::int64_t{1}<<bits)-1,maxv=maxq-1,center=maxv/2;for(std::size_t e=0;e<entries;++e){std::array<std::int64_t,3> nrm{0,0,0};for(int c:incidentCorners(topology,static_cast<std::uint32_t>(e))){const auto centerp=portablePosition(decoded,static_cast<std::uint32_t>(e)),np=portablePosition(decoded,topology.corner_point[static_cast<std::size_t>(Topology::next(c))]),pp=portablePosition(decoded,topology.corner_point[static_cast<std::size_t>(Topology::prev(c))]);const std::array<std::int64_t,3>a={static_cast<std::int64_t>(np[0])-centerp[0],static_cast<std::int64_t>(np[1])-centerp[1],static_cast<std::int64_t>(np[2])-centerp[2]},b={static_cast<std::int64_t>(pp[0])-centerp[0],static_cast<std::int64_t>(pp[1])-centerp[1],static_cast<std::int64_t>(pp[2])-centerp[2]};nrm[0]+=a[1]*b[2]-a[2]*b[1];nrm[1]+=a[2]*b[0]-a[0]*b[2];nrm[2]+=a[0]*b[1]-a[1]*b[0];}canonicalizeIntegerVector(&nrm,center);if(flip_bits[e])for(auto&v:nrm)v=-v;const auto pred=integerVectorToOct(nrm,center,maxv);std::vector<std::int32_t> pv={static_cast<std::int32_t>(pred[0]),static_cast<std::int32_t>(pred[1])};std::vector<std::int32_t> out(2);for(unsigned c=0;c<2;++c){std::int64_t v=pv[c]+corr(e)[c];v%=maxq;if(v<0)v+=maxq;out[c]=static_cast<std::int32_t>(v);}write(e,out);}}
    else return fail(error,"unsupported Draco mesh prediction scheme");
    record->portable=std::move(original);return true;
}
