bool decodeGroupPortable(Reader& r,const Topology& topology,const std::vector<Record>& prior,std::vector<Record> *group,std::string *error){
    if (!group) return false;
    for (Record& record : *group) { const std::size_t entries = topology.point_corner.size();if(record.decoder_type==0u){const std::size_t count=entries*record.output.components;record.output.values.resize(count);for(double& value:record.output.values)if(!rawNumber(r,record.output.data_type,&value))return fail(error,"truncated Draco generic attribute values");}else if(record.decoder_type<=3u){if(!decodeIntegerPortable(r,topology,prior, &record,error))return false;}else return fail(error,"unknown Draco sequential attribute decoder type");}return true;
}

bool applyTransforms(Reader& r,std::vector<Record> *group,std::string *error){if(!group)return false;for(Record& record:*group){const std::size_t entries=record.portable.empty()?0u:record.portable.size()/(record.decoder_type==3u?2u:record.output.components);if(record.decoder_type==2u){std::vector<float> minimum(record.output.components,0.0f);for(float&v:minimum)if(!r.f32(&v))return fail(error,"truncated Draco quantization minimum");float range=0;std::uint8_t bits=0;if(!r.f32(&range)||!r.u8(&bits)||bits==0u||bits>31u)return fail(error,"invalid Draco quantization data");const double denom=static_cast<double>((std::uint64_t{1}<<bits)-1u);record.output.values.resize(entries*record.output.components);for(std::size_t i=0;i<record.output.values.size();++i)record.output.values[i]=minimum[i%record.output.components]+static_cast<double>(record.portable[i])*range/denom;}else if(record.decoder_type==3u){if(record.output.components!=3u||record.output.data_type!=9u)return fail(error,"Draco normal decoder requires float32 vec3");std::uint8_t bits=0;if(!r.u8(&bits)||bits<2u||bits>30u)return fail(error,"invalid Draco normal quantization bits");record.output.values.resize(entries*3u);for(std::size_t i=0;i<entries;++i){double x=0,y=0,z=0;octahedralToUnit(record.portable[i*2u],record.portable[i*2u+1u],bits,&x,&y,&z);record.output.values[i*3u]=x;record.output.values[i*3u+1u]=y;record.output.values[i*3u+2u]=z;}}else if(record.decoder_type==1u){record.output.values.resize(record.portable.size());for(std::size_t i=0;i<record.portable.size();++i)record.output.values[i]=record.portable[i];}}return true;}

bool sequentialConnectivity(Reader& r,DracoMesh *mesh,std::string *error){std::uint32_t faces=0,points=0;std::uint8_t method=0;if(!r.var32(&faces)||!r.var32(&points)||!r.u8(&method))return fail(error,"truncated Draco sequential connectivity header");if(faces>std::numeric_limits<std::size_t>::max()/3u)return fail(error,"Draco face count overflows");mesh->point_count=points;mesh->indices.resize(static_cast<std::size_t>(faces)*3u);if(method==0u){std::vector<std::uint32_t> encoded;if(!decodeSymbols(r,mesh->indices.size(),1u,&encoded))return fail(error,"invalid Draco compressed indices");std::int64_t last=0;for(std::size_t i=0;i<encoded.size();++i){std::int64_t diff=static_cast<std::int64_t>(encoded[i]>>1u);if(encoded[i]&1u)diff=-diff;const std::int64_t value=last+diff;if(value<0||value>=points)return fail(error,"Draco compressed index exceeds point count");mesh->indices[i]=static_cast<std::uint32_t>(value);last=value;}return true;}if(method==1u){for(std::uint32_t& index:mesh->indices){std::uint32_t value=0;if(points<256u){std::uint8_t v=0;if(!r.u8(&v))return fail(error,"truncated Draco UI8 index");value=v;}else if(points<65536u){std::uint16_t v=0;if(!r.u16(&v))return fail(error,"truncated Draco UI16 index");value=v;}else if(points<(1u<<21u)){if(!r.var32(&value))return fail(error,"truncated Draco varuint index");}else if(!r.u32(&value))return fail(error,"truncated Draco UI32 index");if(value>=points)return fail(error,"Draco face index exceeds point count");index=value;}return true;}return fail(error,"unknown Draco sequential connectivity method");}

} // namespace
